"""Shimadzu LabSolutions UV-Vis text-exchange automation."""

from .client import (
    Feedback,
    LabSolutionsBusyError,
    LabSolutionsClient,
    LabSolutionsCommandError,
    LabSolutionsError,
    LabSolutionsProtocolError,
    LabSolutionsRecoveryRequiredError,
    LabSolutionsTimeoutError,
    SpectrumScheduleOverrunError,
    SpectrumRunResult,
    SpectrumSeriesPointResult,
    SpectrumSeriesResult,
    SpectrumSeriesSample,
)
from .batch_workflow import SpectrumBatchController, SpectrumBatchError
from .configuration import (
    ControlSettings,
    MeasurementMode,
    MethodTemplate,
    RuntimeSettings,
    ScanProfile,
    load_settings,
)
from .measurements import (
    MeasurementPurpose,
    MeasurementPlanError,
    MeasurementRequest,
    MethodTemplateRegistry,
    PlanningMode,
    ResolvedMethodTemplate,
    RoutedMeasurementRequest,
    build_measurement_request,
    resolve_method_template,
    route_measurement_request,
)
from .profiles import (
    AmbiguousScanProfileError,
    ResolvedScanProfile,
    ScanProfileNotFoundError,
    ScanProfileRegistry,
    ScanProfileResolutionError,
    SpectrumScanRequest,
    UnknownScanProfileError,
    resolve_scan_profile,
)
from .runtime_manager import (
    LabSolutionsRuntimeError,
    LabSolutionsRuntimeManager,
    RuntimeReady,
)

__all__ = [
    "Feedback",
    "AmbiguousScanProfileError",
    "ControlSettings",
    "LabSolutionsBusyError",
    "LabSolutionsClient",
    "LabSolutionsCommandError",
    "LabSolutionsError",
    "LabSolutionsProtocolError",
    "LabSolutionsRecoveryRequiredError",
    "LabSolutionsTimeoutError",
    "MeasurementMode",
    "MeasurementPurpose",
    "MeasurementPlanError",
    "MeasurementRequest",
    "MethodTemplate",
    "MethodTemplateRegistry",
    "PlanningMode",
    "ScanProfile",
    "ResolvedScanProfile",
    "ResolvedMethodTemplate",
    "RoutedMeasurementRequest",
    "RuntimeReady",
    "RuntimeSettings",
    "ScanProfileNotFoundError",
    "ScanProfileRegistry",
    "ScanProfileResolutionError",
    "SpectrumScanRequest",
    "SpectrumScheduleOverrunError",
    "SpectrumBatchController",
    "SpectrumBatchError",
    "SpectrumRunResult",
    "SpectrumSeriesPointResult",
    "SpectrumSeriesResult",
    "SpectrumSeriesSample",
    "UnknownScanProfileError",
    "LabSolutionsRuntimeError",
    "LabSolutionsRuntimeManager",
    "build_measurement_request",
    "load_settings",
    "resolve_scan_profile",
    "resolve_method_template",
    "route_measurement_request",
]

__version__ = "0.5.0"
